### ISSUE TITLE
BuildGradleFileContributor cannot generate Gradle 3 compliant builds

### ISSUE THREAD

**Issue by snicoll** [wilkinsona/project-generator#25]
We still need to support Gradle 3 and compile-scoped dependencies can't use `implementation`. We probably a notion of "generation" for the writer. 

Arguably, that code should also be moved to the base module given the language writers are located there.

**Comment by wilkinsona** [comment]
The `implementation` configuration was introduced in Gradle 3.4. We currently use Gradle 3.5 for projects that need Gradle 3 (use Boot 1.5). Isn't that sufficient? All of the integration tests that use Gradle and Boot 1.5 pass at the moment.

**Comment by snicoll** [comment]
I reported this as tests in the main projects were failing. We have an issue to deprecate "old stuff" (pre 1.5) so perhaps I should get going and just remove the support there as well?
