### ISSUE TITLE
Provide an enum for standard build systems

### ISSUE THREAD

**Issue by wilkinsona** [wilkinsona/project-generator#5]
Similar to the JDK's `java.nio.files.CopyAction` and `java.nio.files.StandardCopyAction` we could provide an enum for the standard build systems while still retaining extensibility.

**Comment by wilkinsona** [comment]
Unfortunately, I'm not sure that this is going to work out. [This](
https://github.com/wilkinsona/project-generator/tree/standard-build-systems) is roughly what I had in mind. See the commit comment for details.

**Comment by snicoll** [comment]
I think we can forget about this one for now.
