### ISSUE TITLE
Build file should contain kotlin jpa plugin when language is kotlin and jpa facet present

### ISSUE THREAD

**Issue by mbhave** [wilkinsona/project-generator#64]

**Comment by mbhave** [comment]
The fix for this is [here](https://github.com/mbhave/initializr/commit/fba351e7f56924a69625290acdb5f1aff5212838).

**Comment by snicoll** [comment]
I've added a minor comment, ship it 👍

**Comment by mbhave** [comment]
Closed by [this](https://github.com/spring-io/initializr/commit/41d11389f6dd638af5193f353d12ecea237a914d) commit.
