### ISSUE TITLE
Spring Boot version missing when maven project is generated with custom parent and spring boot bom

### ISSUE THREAD

**Issue by mbhave** [wilkinsona/project-generator#68]

**Comment by mbhave** [comment]
@snicoll I think [this](https://github.com/mbhave/initializr/commit/58746c71166e9d30dade4d905670b24c24ffe33d#diff-ba73499a03ca440de7d122274fe667a3R56) is the fix or have I misunderstood what that condition is supposed to check?

**Comment by snicoll** [comment]
For the record the test failing in the existing infrastructure is `mavenPomWithCustomParentPomAndSpringBootBom`

**Comment by snicoll** [comment]
@mbhave nope you're right. I've fixed the condition in the branch, thank you!
