### ISSUE TITLE
build.gradle has extra newline

### ISSUE THREAD

**Issue by mbhave** [wilkinsona/project-generator#71]

**Comment by mbhave** [comment]
need to investigate why (this test)[https://github.com/wilkinsona/project-generator/blob/master/initializr-generator-project/src/test/java/io/spring/initializr/generator/project/ProjectGeneratorTests.java#L127] is green even though there are two new lines at the end.

**Comment by snicoll** [comment]
There aren't two new lines at the end. How can I reproduce this?

**Comment by mbhave** [comment]
I think `Files.readAllLines` doesn't see the extra line because it's an empty line. It sees the previous one because it has the `\n` character.

**Comment by snicoll** [comment]
Good catch. I've been trying different options this afternoon to get that extra line and didn't manage to do so. It looks like we need a new line or EOF signal or something.

**Comment by snicoll** [comment]
This drives me nuts. I have the same problem on another component that I've refactored. It looks like that if the `Writer` ends with an empty new line, "something" is adding a carriage return.
