### ISSUE TITLE
Fix metrics handling

### ISSUE THREAD

**Issue by snicoll** [wilkinsona/project-generator#86]
Now that we've stopped resolving `ProjectRequest` (as it should be) part of the request is no longer in a proper state (especially when the request has succeeded). 

When the request is successful, no dependencies have been resolved, so [this call returns an empty list](https://github.com/spring-io/initializr/blob/33eea01b62137fa3d7bde59bb9b874a6d57b851c/initializr-actuator/src/main/java/io/spring/initializr/actuate/metric/ProjectGenerationMetricsListener.java#L68).

I guess I was wrong when I thought keeping only the request was enough. I am afraid we won't have much of a choice to add a dependency between "web" and "actuator" as the event is likely to move there (as is event management at the moment). That should have happened in any case as we need a new home for `Agent`.

**Comment by snicoll** [comment]
@mbhave looks like we're good there now, right?

**Comment by mbhave** [comment]
yup, I'll close it.
